# -*- coding: utf-8 -*-
"""LVADSUSR134_SANJU_YADAV_LAB2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NM_2xaJPvWI7KCiQ6117LUGgTgQUH9e_
"""

import pandas as pd
data = pd.read_csv('/content/Mall_Customers.csv')
data.info()

import pandas as pd
from sklearn.preprocessing import StandardScaler
data['Annual Income (k$)'].fillna(data['Annual Income (k$)'].median(), inplace=True)
scaler = StandardScaler()
data[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']] = scaler.fit_transform(data[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']])

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Elbow Method
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
    kmeans.fit(data[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']])
    wcss.append(kmeans.inertia_)
plt.plot(range(1, 11), wcss)
plt.title('Elbow Method')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

# Silhouette Score
from sklearn.metrics import silhouette_score
silhouette_scores = []
for n_clusters in range(2, 11):
    kmeans = KMeans(n_clusters=n_clusters, init='k-means++', random_state=42)
    kmeans.fit(data[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']])
    silhouette_scores.append(silhouette_score(data[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']], kmeans.labels_))
plt.plot(range(2, 11), silhouette_scores)
plt.title('Silhouette Score')
plt.xlabel('Number of Clusters')
plt.ylabel('Silhouette Score')
plt.show()

kmeans = KMeans(n_clusters=5, init='k-means++', random_state=42)
kmeans.fit(data[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']])
data['Cluster'] = kmeans.labels_

cluster_profile = data.groupby('Cluster').mean()
print(cluster_profile)

"""Segment-Specific Marketing: Tailor promotions and marketing campaigns to each cluster's preferences and behaviors. For example, offer luxury product promotions to high-income clusters and budget-friendly deals to price-sensitive clusters.

Personalized Communication: Craft personalized messages and advertisements targeted at each cluster. Use demographic and behavioral insights to customize communication channels and messaging.

Product Recommendations: Provide customized product recommendations based on each cluster's preferences. Use data analytics to suggest relevant products and promotions to customers within each segment.

Customer Experience Enhancement: Enhance the shopping experience based on cluster characteristics. Implement tailored services, improve product assortment, and optimize pricing strategies to better meet the needs of each cluster.

Iterative Improvement: Continuously evaluate the effectiveness of strategies for each cluster. Monitor key performance indicators and adjust marketing tactics and customer experiences accordingly to optimize results.
"""



























